"""Canonical reasoning-event contracts and integrity verification."""

from deductra.reasoning.engine import (
    DeductionAuthority,
    DeductionAuthorityResult,
    DeductionAuthorityStatus,
    HumanReasoningAttempt,
    HumanReasoningEngine,
    HumanSolveContext,
    HumanSolveStatus,
    HumanSolveTrace,
    compute_human_trace_hash,
)
from deductra.reasoning.events import (
    BranchClosed,
    BranchOpened,
    CandidatesEliminated,
    ContradictionDetected,
    EventEnvelope,
    InitialStateCreated,
    ProducerRef,
    PuzzleValidated,
    TraceCompleted,
    TraceFailed,
    TraceStarted,
    ValueAssigned,
)
from deductra.reasoning.integrity import (
    GENESIS_EVENT_HASH,
    ChainVerification,
    compute_event_hash,
    seal_event,
    verify_chain,
    verify_event,
)
from deductra.reasoning.policy import ReasoningPolicy, select_rule_application
from deductra.reasoning.reducer import (
    SearchDisclosureError,
    StateConflictError,
    StateReductionError,
    UnsupportedStateEventError,
    reduce_state,
    replay_projection,
)
from deductra.reasoning.rules import (
    ProposedDeduction,
    ReasoningRule,
    RuleApplicationCandidate,
    RuleContractError,
    RuleReference,
    discover_rule_applications,
)
from deductra.reasoning.state import (
    PuzzleState,
    StateValidation,
    compute_state_hash,
    create_initial_state,
    validate_state,
)

__all__ = [
    "GENESIS_EVENT_HASH",
    "BranchClosed",
    "BranchOpened",
    "CandidatesEliminated",
    "ChainVerification",
    "ContradictionDetected",
    "DeductionAuthority",
    "DeductionAuthorityResult",
    "DeductionAuthorityStatus",
    "EventEnvelope",
    "HumanReasoningAttempt",
    "HumanReasoningEngine",
    "HumanSolveContext",
    "HumanSolveStatus",
    "HumanSolveTrace",
    "InitialStateCreated",
    "ProducerRef",
    "ProposedDeduction",
    "PuzzleState",
    "PuzzleValidated",
    "ReasoningPolicy",
    "ReasoningRule",
    "RuleApplicationCandidate",
    "RuleContractError",
    "RuleReference",
    "SearchDisclosureError",
    "StateConflictError",
    "StateReductionError",
    "StateValidation",
    "TraceCompleted",
    "TraceFailed",
    "TraceStarted",
    "UnsupportedStateEventError",
    "ValueAssigned",
    "compute_event_hash",
    "compute_human_trace_hash",
    "compute_state_hash",
    "create_initial_state",
    "discover_rule_applications",
    "reduce_state",
    "replay_projection",
    "seal_event",
    "select_rule_application",
    "validate_state",
    "verify_chain",
    "verify_event",
]
